# Generated by Django 4.0.2 on 2022-03-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_choices',
            field=models.CharField(choices=[('1', 'Administrator'), ('2', 'Staff'), ('3', 'Merchant'), ('4', 'Customer')], default='4', max_length=31),
        ),
    ]
