# Generated by Django 4.0.2 on 2022-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_alter_user_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_choices',
            field=models.CharField(choices=[('1', 'Administrator'), ('2', 'Staff'), ('3', 'Merchant'), ('4', 'Customer')], default='4', max_length=1),
        ),
    ]
