# Generated by Django 4.0.2 on 2022-03-08 18:33

from django.db import migrations, models
import v1.accounts.managers.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_type_choices'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', v1.accounts.managers.user_manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_choices',
        ),
        migrations.AddField(
            model_name='user',
            name='type_choice',
            field=models.CharField(choices=[(1, 'Administrator'), (2, 'Staff'), (3, 'Merchant'), (4, 'Customer')], default=4, max_length=1),
        ),
    ]
