services:
  web:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/local.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/app

  web_prod:
    build:
      context: .
      args:
        REQUIREMENTS: requirements/production.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app

  frontend:
    build:
      context: ../allegro-clone-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://web:8000
    volumes:
      - ../allegro-clone-frontend:/app
    depends_on:
      - web

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
