FROM python:3.11.7

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY README.md /app/README.md
COPY Dockerfile.dev /app/Dockerfile.dev
COPY entrypoint.sh /app/entrypoint.sh
COPY media /app/media
COPY requirements /app/requirements
COPY v1 /app/v1
COPY config /app/config
COPY docker-compose.dev.yml /app/docker-compose.dev.yml
COPY load_sample_data.sh /app/load_sample_data.sh
COPY manage.py /app/manage.py

RUN pip install --no-cache-dir -r /app/requirements/development.txt

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

RUN chmod +x /app/load_sample_data.sh /app/entrypoint.sh
RUN sed -i 's/\r$//' /app/load_sample_data.sh &&  sed -i 's/\r$//' /app/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]
