# Generated by Django 4.0.2 on 2022-02-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_roles', '0002_rename_gst_details_merchant_get_details_customer'),
        ('product_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewVoting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_reviews.productreview')),
                ('user_id_voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.customer')),
            ],
        ),
    ]
