INSERT INTO product_reviews_productreview (id, product_id_id, user_id_id, review_image, rating, review, created_at, is_active) VALUES
(1, 1, 1, 'review1_image.jpg', '5', 'Amazing product! Highly recommend.', CURRENT_TIMESTAMP, TRUE),
(2, 1, 2, 'review2_image.jpg', '4', 'Great phone, but battery life could be better.', CURRENT_TIMESTAMP, TRUE),
(3, 2, 3, 'review3_image.jpg', '5', 'Perfect laptop for work and travel.', CURRENT_TIMESTAMP, TRUE),
(4, 2, 4, 'review4_image.jpg', '4', 'Lightweight but heats up sometimes.', CURRENT_TIMESTAMP, TRUE),
(5, 3, 5, 'review5_image.jpg', '5', 'Excellent camera for photography lovers.', CURRENT_TIMESTAMP, TRUE),
(6, 3, 6, 'review6_image.jpg', '4', 'Great camera, but lens is a bit expensive.', CURRENT_TIMESTAMP, TRUE),
(7, 4, 7, 'review7_image.jpg', '5', 'Stylish and comfortable jacket.', CURRENT_TIMESTAMP, TRUE),
(8, 4, 8, 'review8_image.jpg', '4', 'Good quality, but a bit pricey.', CURRENT_TIMESTAMP, TRUE),
(9, 5, 9, 'review9_image.jpg', '5', 'Beautiful dress, perfect for special occasions.', CURRENT_TIMESTAMP, TRUE),
(10, 5, 10, 'review10_image.jpg', '4', 'Looks amazing, but sizing is tricky.', CURRENT_TIMESTAMP, TRUE),
(11, 6, 1, 'review11_image.jpg', '5', 'Elegant earrings with great quality.', CURRENT_TIMESTAMP, TRUE),
(12, 6, 2, 'review12_image.jpg', '4', 'Very nice, but slightly heavy.', CURRENT_TIMESTAMP, TRUE),
(13, 7, 3, 'review13_image.jpg', '5', 'Comfortable sofa, looks great in my living room.', CURRENT_TIMESTAMP, TRUE),
(14, 7, 4, 'review14_image.jpg', '4', 'Nice design but material could be softer.', CURRENT_TIMESTAMP, TRUE),
(15, 8, 5, 'review15_image.jpg', '5', 'Durable shovel, great for gardening.', CURRENT_TIMESTAMP, TRUE),
(16, 8, 6, 'review16_image.jpg', '4', 'Works well, but handle feels slippery.', CURRENT_TIMESTAMP, TRUE),
(17, 9, 7, 'review17_image.jpg', '5', 'Beautiful painting, perfect for my living room.', CURRENT_TIMESTAMP, TRUE),
(18, 9, 8, 'review18_image.jpg', '4', 'Looks nice, but colors are slightly different.', CURRENT_TIMESTAMP, TRUE),
(19, 10, 9, 'review19_image.jpg', '5', 'Excellent treadmill for home workouts.', CURRENT_TIMESTAMP, TRUE),
(20, 10, 10, 'review20_image.jpg', '4', 'Good features, but assembly took time.', CURRENT_TIMESTAMP, TRUE),
(21, 11, 1, 'review21_image.jpg', '5', 'Perfect tent for camping trips.', CURRENT_TIMESTAMP, TRUE),
(22, 11, 2, 'review22_image.jpg', '4', 'Easy to set up, but poles feel flimsy.', CURRENT_TIMESTAMP, TRUE),
(23, 12, 3, 'review23_image.jpg', '5', 'Great quality football kit.', CURRENT_TIMESTAMP, TRUE),
(24, 12, 4, 'review24_image.jpg', '4', 'Looks good but fits snug.', CURRENT_TIMESTAMP, TRUE),
(25, 13, 5, 'review25_image.jpg', '5', 'Keeps my skin hydrated all day.', CURRENT_TIMESTAMP, TRUE),
(26, 13, 6, 'review26_image.jpg', '4', 'Works well but has a strong scent.', CURRENT_TIMESTAMP, TRUE),
(27, 14, 7, 'review27_image.jpg', '5', 'Vibrant colors and long-lasting.', CURRENT_TIMESTAMP, TRUE),
(28, 14, 8, 'review28_image.jpg', '4', 'Good quality but dries out fast.', CURRENT_TIMESTAMP, TRUE),
(29, 15, 9, 'review29_image.jpg', '5', 'Boosted my immune system effectively.', CURRENT_TIMESTAMP, TRUE),
(30, 15, 10, 'review30_image.jpg', '4', 'Effective, but packaging could be better.', CURRENT_TIMESTAMP, TRUE),
(31, 16, 1, 'review31_image.jpg', '5', 'Amazing collectible figure.', CURRENT_TIMESTAMP, TRUE),
(32, 16, 2, 'review32_image.jpg', '4', 'Great quality, but a bit fragile.', CURRENT_TIMESTAMP, TRUE),
(33, 17, 3, 'review33_image.jpg', '5', 'Excellent learning toy for kids.', CURRENT_TIMESTAMP, TRUE),
(34, 17, 4, 'review34_image.jpg', '4', 'Good toy, but a bit complex for younger kids.', CURRENT_TIMESTAMP, TRUE),
(35, 18, 5, 'review35_image.jpg', '5', 'Classic chessboard, great quality.', CURRENT_TIMESTAMP, TRUE),
(36, 18, 6, 'review36_image.jpg', '4', 'Nice board but pieces are light.', CURRENT_TIMESTAMP, TRUE),
(37, 19, 7, 'review37_image.jpg', '5', 'Secure phone holder for my car.', CURRENT_TIMESTAMP, TRUE),
(38, 19, 8, 'review38_image.jpg', '4', 'Works well, but suction cup is weak.', CURRENT_TIMESTAMP, TRUE),
(39, 20, 9, 'review39_image.jpg', '5', 'Durable helmet with great protection.', CURRENT_TIMESTAMP, TRUE),
(40, 20, 10, 'review40_image.jpg', '4', 'Comfortable, but slightly heavy.', CURRENT_TIMESTAMP, TRUE);
