INSERT INTO product_questions_productquestion (id, product_id_id, user_id_id, question, answer, created_at, is_active) VALUES
(1, 1, 1, 'Does the iPhone 15 support 5G?', 'Yes, it supports 5G connectivity.', CURRENT_TIMESTAMP, TRUE),
(2, 1, 2, 'What is the battery life of the iPhone 15?', 'It lasts up to 18 hours with typical use.', CURRENT_TIMESTAMP, TRUE),
(3, 2, 3, 'Does the MacBook Air come with a warranty?', 'Yes, it includes a one-year limited warranty.', CURRENT_TIMESTAMP, TRUE),
(4, 2, 4, 'Is the MacBook Air suitable for gaming?', 'It can handle light gaming, but it is not designed for heavy gaming.', CURRENT_TIMESTAMP, TRUE),
(5, 3, 5, 'What lenses are compatible with the Canon EOS R10?', 'The Canon EOS R10 is compatible with RF lenses.', CURRENT_TIMESTAMP, TRUE),
(6, 3, 6, 'Does the camera include an SD card?', 'No, the SD card is sold separately.', CURRENT_TIMESTAMP, TRUE),
(7, 4, 7, 'What is the material of the leather jacket?', 'It is made of 100% genuine leather.', CURRENT_TIMESTAMP, TRUE),
(8, 4, 8, 'Can the jacket be cleaned in a washing machine?', 'No, it should be dry-cleaned only.', CURRENT_TIMESTAMP, TRUE),
(9, 5, 9, 'Is the evening dress true to size?', 'Yes, but we recommend checking the size chart before purchasing.', CURRENT_TIMESTAMP, TRUE),
(10, 5, 10, 'Can the dress be machine washed?', 'Yes, it is machine washable.', CURRENT_TIMESTAMP, TRUE),
(11, 6, 1, 'What is the weight of the gold earrings?', 'The earrings weigh approximately 5 grams each.', CURRENT_TIMESTAMP, TRUE),
(12, 6, 2, 'Are the earrings hypoallergenic?', 'Yes, they are designed to be hypoallergenic.', CURRENT_TIMESTAMP, TRUE),
(13, 7, 3, 'Does the sofa come assembled?', 'No, it requires basic assembly.', CURRENT_TIMESTAMP, TRUE),
(14, 7, 4, 'Is the fabric of the sofa stain-resistant?', 'Yes, it is designed to resist common stains.', CURRENT_TIMESTAMP, TRUE),
(15, 8, 5, 'What is the length of the gardening shovel?', 'It is 40 inches long.', CURRENT_TIMESTAMP, TRUE),
(16, 8, 6, 'Is the shovel handle ergonomic?', 'Yes, it features an ergonomic handle for comfortable use.', CURRENT_TIMESTAMP, TRUE),
(17, 9, 7, 'What are the dimensions of the wall painting?', 'The painting measures 24x36 inches.', CURRENT_TIMESTAMP, TRUE),
(18, 9, 8, 'Is the painting framed?', 'No, it is sold without a frame.', CURRENT_TIMESTAMP, TRUE),
(19, 10, 9, 'What is the maximum weight capacity of the treadmill?', 'The treadmill supports up to 300 lbs.', CURRENT_TIMESTAMP, TRUE),
(20, 10, 10, 'Does the treadmill have a heart rate monitor?', 'Yes, it includes a built-in heart rate monitor.', CURRENT_TIMESTAMP, TRUE),
(21, 11, 1, 'Is the camping tent waterproof?', 'Yes, it is fully waterproof.', CURRENT_TIMESTAMP, TRUE),
(22, 11, 2, 'How many people can the tent accommodate?', 'It can accommodate up to 4 people.', CURRENT_TIMESTAMP, TRUE),
(23, 12, 3, 'What material is the football kit made of?', 'It is made of high-quality polyester.', CURRENT_TIMESTAMP, TRUE),
(24, 12, 4, 'Does the kit include socks?', 'Yes, the kit includes matching socks.', CURRENT_TIMESTAMP, TRUE),
(25, 13, 5, 'Is the moisturizing cream suitable for sensitive skin?', 'Yes, it is dermatologically tested for sensitive skin.', CURRENT_TIMESTAMP, TRUE),
(26, 13, 6, 'Does the cream contain any fragrance?', 'No, it is fragrance-free.', CURRENT_TIMESTAMP, TRUE),
(27, 14, 7, 'Are the lipsticks long-lasting?', 'Yes, they are designed to last up to 8 hours.', CURRENT_TIMESTAMP, TRUE),
(28, 14, 8, 'Are the lipsticks vegan?', 'Yes, they are vegan and cruelty-free.', CURRENT_TIMESTAMP, TRUE),
(29, 15, 9, 'Are the Vitamin C tablets chewable?', 'Yes, they are easy to chew and swallow.', CURRENT_TIMESTAMP, TRUE),
(30, 15, 10, 'What is the recommended dosage for the tablets?', 'The recommended dosage is one tablet per day.', CURRENT_TIMESTAMP, TRUE),
(31, 16, 1, 'What is the height of the superhero figure?', 'It is 12 inches tall.', CURRENT_TIMESTAMP, TRUE),
(32, 16, 2, 'Is the figure poseable?', 'Yes, it has multiple points of articulation.', CURRENT_TIMESTAMP, TRUE),
(33, 17, 3, 'What age group is the math toy suitable for?', 'It is designed for children aged 6-10.', CURRENT_TIMESTAMP, TRUE),
(34, 17, 4, 'Does the toy require batteries?', 'No, it does not require batteries.', CURRENT_TIMESTAMP, TRUE),
(35, 18, 5, 'Is the chess board magnetic?', 'Yes, it has magnetic pieces.', CURRENT_TIMESTAMP, TRUE),
(36, 18, 6, 'What are the dimensions of the chess board?', 'It measures 15x15 inches.', CURRENT_TIMESTAMP, TRUE),
(37, 19, 7, 'Can the phone holder rotate?', 'Yes, it can rotate 360 degrees.', CURRENT_TIMESTAMP, TRUE),
(38, 19, 8, 'Is the phone holder compatible with all phones?', 'Yes, it is adjustable to fit most phone sizes.', CURRENT_TIMESTAMP, TRUE),
(39, 20, 9, 'What sizes are available for the helmet?', 'It is available in small, medium, and large.', CURRENT_TIMESTAMP, TRUE),
(40, 20, 10, 'Is the helmet DOT certified?', 'Yes, it meets DOT safety standards.', CURRENT_TIMESTAMP, TRUE);
