INSERT INTO product_variant_items_productvariantitem (id, product_varient_id_id, product_id_id, title, created_at) VALUES
(1, 1, 1, 'iPhone 15 - 128GB', CURRENT_TIMESTAMP),
(2, 2, 1, 'iPhone 15 - 256GB', CURRENT_TIMESTAMP),
(3, 3, 2, 'MacBook Air - 13-inch', CURRENT_TIMESTAMP),
(4, 4, 2, 'MacBook Air - 15-inch', CURRENT_TIMESTAMP),
(5, 5, 3, 'Canon EOS R10 - Body Only', CURRENT_TIMESTAMP),
(6, 6, 3, 'Canon EOS R10 - With Lens Kit', CURRENT_TIMESTAMP),
(7, 7, 4, 'Mens Leather Jacket - Black', CURRENT_TIMESTAMP),
(8, 8, 4, 'Mens Leather Jacket - Brown', CURRENT_TIMESTAMP),
(9, 9, 5, 'Women''s Evening Dress - Red', CURRENT_TIMESTAMP),
(10, 10, 5, 'Women''s Evening Dress - Blue', CURRENT_TIMESTAMP),
(11, 11, 6, 'Gold Earrings - 18k', CURRENT_TIMESTAMP),
(12, 12, 6, 'Gold Earrings - 24k', CURRENT_TIMESTAMP),
(13, 13, 7, 'Modern Sofa - 3-Seater', CURRENT_TIMESTAMP),
(14, 14, 7, 'Modern Sofa - L-Shape', CURRENT_TIMESTAMP),
(15, 15, 8, 'Gardening Shovel - Small', CURRENT_TIMESTAMP),
(16, 16, 8, 'Gardening Shovel - Large', CURRENT_TIMESTAMP),
(17, 17, 9, 'Wall Painting - Abstract', CURRENT_TIMESTAMP),
(18, 18, 9, 'Wall Painting - Landscape', CURRENT_TIMESTAMP),
(19, 19, 10, 'Treadmill Pro - Standard', CURRENT_TIMESTAMP),
(20, 20, 10, 'Treadmill Pro - Advanced', CURRENT_TIMESTAMP),
(21, 21, 11, 'Camping Tent - 2 Person', CURRENT_TIMESTAMP),
(22, 22, 11, 'Camping Tent - 4 Person', CURRENT_TIMESTAMP),
(23, 23, 12, 'Football Kit - Home', CURRENT_TIMESTAMP),
(24, 24, 12, 'Football Kit - Away', CURRENT_TIMESTAMP),
(25, 25, 13, 'Moisturizing Cream - 50ml', CURRENT_TIMESTAMP),
(26, 26, 13, 'Moisturizing Cream - 100ml', CURRENT_TIMESTAMP),
(27, 27, 14, 'Lipstick Set - Matte', CURRENT_TIMESTAMP),
(28, 28, 14, 'Lipstick Set - Glossy', CURRENT_TIMESTAMP),
(29, 29, 15, 'Vitamin C Tablets - 30-pack', CURRENT_TIMESTAMP),
(30, 30, 15, 'Vitamin C Tablets - 60-pack', CURRENT_TIMESTAMP),
(31, 31, 16, 'Superhero Figure - Classic', CURRENT_TIMESTAMP),
(32, 32, 16, 'Superhero Figure - Limited Edition', CURRENT_TIMESTAMP),
(33, 33, 17, 'Math Learning Toy - Basic', CURRENT_TIMESTAMP),
(34, 34, 17, 'Math Learning Toy - Advanced', CURRENT_TIMESTAMP),
(35, 35, 18, 'Chess Board - Wooden', CURRENT_TIMESTAMP),
(36, 36, 18, 'Chess Board - Magnetic', CURRENT_TIMESTAMP),
(37, 37, 19, 'Car Phone Holder - Dashboard', CURRENT_TIMESTAMP),
(38, 38, 19, 'Car Phone Holder - Windshield', CURRENT_TIMESTAMP),
(39, 39, 20, 'Motorbike Helmet - Full Face', CURRENT_TIMESTAMP),
(40, 40, 20, 'Motorbike Helmet - Open Face', CURRENT_TIMESTAMP);
