INSERT INTO product_details_productdetail (id, product_id_id, title, title_details, created_at, is_active) VALUES
(1, 1, 'Display', '6.1-inch Super Retina XDR', CURRENT_TIMESTAMP, TRUE),
(2, 1, 'Processor', 'A16 Bionic Chip', CURRENT_TIMESTAMP, TRUE),
(3, 2, 'Weight', '2.8 lbs', CURRENT_TIMESTAMP, TRUE),
(4, 2, 'Battery Life', 'Up to 18 hours', CURRENT_TIMESTAMP, TRUE),
(5, 3, 'Resolution', '24.2 megapixels', CURRENT_TIMESTAMP, TRUE),
(6, 3, 'Lens Mount', 'Canon RF Mount', CURRENT_TIMESTAMP, TRUE),
(7, 4, 'Material', 'Genuine Leather', CURRENT_TIMESTAMP, TRUE),
(8, 4, 'Color Options', 'Black, Brown', CURRENT_TIMESTAMP, TRUE),
(9, 5, 'Material', 'Polyester and Lace', CURRENT_TIMESTAMP, TRUE),
(10, 5, 'Available Sizes', 'S, M, L, XL', CURRENT_TIMESTAMP, TRUE),
(11, 6, 'Material', '18k Gold', CURRENT_TIMESTAMP, TRUE),
(12, 6, 'Weight', '5 grams', CURRENT_TIMESTAMP, TRUE),
(13, 7, 'Dimensions', '80x35x30 inches', CURRENT_TIMESTAMP, TRUE),
(14, 7, 'Fabric', 'Stain-Resistant Polyester', CURRENT_TIMESTAMP, TRUE),
(15, 8, 'Material', 'Steel and Plastic', CURRENT_TIMESTAMP, TRUE),
(16, 8, 'Length', '40 inches', CURRENT_TIMESTAMP, TRUE),
(17, 9, 'Dimensions', '24x36 inches', CURRENT_TIMESTAMP, TRUE),
(18, 9, 'Theme', 'Abstract, Landscape', CURRENT_TIMESTAMP, TRUE),
(19, 10, 'Max Weight Capacity', '300 lbs', CURRENT_TIMESTAMP, TRUE),
(20, 10, 'Features', 'Heart Rate Monitor, Foldable', CURRENT_TIMESTAMP, TRUE),
(21, 11, 'Capacity', '2-4 People', CURRENT_TIMESTAMP, TRUE),
(22, 11, 'Waterproof', 'Yes', CURRENT_TIMESTAMP, TRUE),
(23, 12, 'Material', 'High-Quality Polyester', CURRENT_TIMESTAMP, TRUE),
(24, 12, 'Includes', 'Jersey, Shorts, Socks', CURRENT_TIMESTAMP, TRUE),
(25, 13, 'Volume', '50ml', CURRENT_TIMESTAMP, TRUE),
(26, 13, 'Features', 'Fragrance-Free, For Sensitive Skin', CURRENT_TIMESTAMP, TRUE),
(27, 14, 'Colors', 'Matte, Glossy', CURRENT_TIMESTAMP, TRUE),
(28, 14, 'Lasting Time', 'Up to 8 hours', CURRENT_TIMESTAMP, TRUE),
(29, 15, 'Form', 'Chewable Tablets', CURRENT_TIMESTAMP, TRUE),
(30, 15, 'Dosage', '1 tablet per day', CURRENT_TIMESTAMP, TRUE),
(31, 16, 'Height', '12 inches', CURRENT_TIMESTAMP, TRUE),
(32, 16, 'Articulation', 'Multiple Poseable Points', CURRENT_TIMESTAMP, TRUE),
(33, 17, 'Age Group', '6-10 years', CURRENT_TIMESTAMP, TRUE),
(34, 17, 'Batteries Required', 'No', CURRENT_TIMESTAMP, TRUE),
(35, 18, 'Type', 'Wooden, Magnetic', CURRENT_TIMESTAMP, TRUE),
(36, 18, 'Dimensions', '15x15 inches', CURRENT_TIMESTAMP, TRUE),
(37, 19, 'Rotation', '360 degrees', CURRENT_TIMESTAMP, TRUE),
(38, 19, 'Compatibility', 'Most Phones', CURRENT_TIMESTAMP, TRUE),
(39, 20, 'Sizes', 'S, M, L', CURRENT_TIMESTAMP, TRUE),
(40, 20, 'Safety Standard', 'DOT Certified', CURRENT_TIMESTAMP, TRUE);
