INSERT INTO product_abouts_productabout (id, product_id_id, title, created_at, is_active) VALUES
(1, 1, 'Next-generation smartphone with advanced features.', DATETIME('now'), 1),
(2, 1, 'Supports 5G connectivity for blazing-fast internet.', DATETIME('now'), 1),
(3, 1, 'Made with durable materials and a sleek design.', DATETIME('now'), 1),
(4, 2, 'Lightweight laptop ideal for professionals on the go.', DATETIME('now'), 1),
(5, 2, 'Powered by the M2 chip for exceptional performance.', DATETIME('now'), 1),
(6, 2, 'Up to 18 hours of battery life for all-day use.', DATETIME('now'), 1),
(7, 3, 'Compact and versatile mirrorless camera.', DATETIME('now'), 1),
(8, 3, '24.2 MP resolution for high-quality photos.', DATETIME('now'), 1),
(9, 3, 'Compatible with a wide range of Canon RF lenses.', DATETIME('now'), 1),
(10, 4, 'Stylish and durable leather jacket for men.', DATETIME('now'), 1),
(11, 4, 'Available in multiple colors and sizes.', DATETIME('now'), 1),
(12, 4, 'Designed for comfort and long-lasting wear.', DATETIME('now'), 1),
(13, 5, 'Elegant evening dress for special occasions.', DATETIME('now'), 1),
(14, 5, 'Made with high-quality polyester and lace.', DATETIME('now'), 1),
(15, 5, 'Perfect fit with adjustable straps.', DATETIME('now'), 1),
(16, 6, 'Exquisite gold earrings for any occasion.', DATETIME('now'), 1),
(17, 6, 'Hypoallergenic and lightweight design.', DATETIME('now'), 1),
(18, 6, 'Available in 18k and 24k options.', DATETIME('now'), 1),
(19, 7, 'Modern sofa designed for maximum comfort.', DATETIME('now'), 1),
(20, 7, 'Features a stain-resistant fabric.', DATETIME('now'), 1),
(21, 7, 'Available in multiple configurations.', DATETIME('now'), 1),
(22, 8, 'Durable gardening shovel with ergonomic handle.', DATETIME('now'), 1),
(23, 8, 'Made from high-quality steel for long-lasting use.', DATETIME('now'), 1),
(24, 8, 'Ideal for both beginners and professionals.', DATETIME('now'), 1),
(25, 9, 'Beautiful wall painting to enhance your decor.', DATETIME('now'), 1),
(26, 9, 'Available in abstract and landscape designs.', DATETIME('now'), 1),
(27, 9, 'Perfect gift for art lovers.', DATETIME('now'), 1),
(28, 10, 'High-performance treadmill for home workouts.', DATETIME('now'), 1),
(29, 10, 'Features a foldable design for easy storage.', DATETIME('now'), 1),
(30, 10, 'Includes a heart rate monitor.', DATETIME('now'), 1),
(31, 11, 'Reliable tent designed for outdoor adventures.', DATETIME('now'), 1),
(32, 11, 'Fully waterproof with sturdy poles.', DATETIME('now'), 1),
(33, 11, 'Fits up to 4 people comfortably.', DATETIME('now'), 1),
(34, 12, 'High-quality football kit for players and teams.', DATETIME('now'), 1),
(35, 12, 'Includes jersey, shorts, and socks.', DATETIME('now'), 1),
(36, 12, 'Breathable material for enhanced comfort.', DATETIME('now'), 1),
(37, 13, 'Premium moisturizing cream for healthy skin.', DATETIME('now'), 1),
(38, 13, 'Fragrance-free and suitable for sensitive skin.', DATETIME('now'), 1),
(39, 13, 'Provides 24-hour hydration.', DATETIME('now'), 1),
(40, 14, 'Vibrant lipstick set for a flawless look.', DATETIME('now'), 1),
(41, 14, 'Available in matte and glossy finishes.', DATETIME('now'), 1),
(42, 14, 'Long-lasting and easy to apply.', DATETIME('now'), 1),
(43, 15, 'Boosts immunity with essential nutrients.', DATETIME('now'), 1),
(44, 15, 'Easy-to-chew Vitamin C tablets.', DATETIME('now'), 1),
(45, 15, 'Recommended dosage: one tablet per day.', DATETIME('now'), 1),
(46, 16, 'Collectible superhero figure for enthusiasts.', DATETIME('now'), 1),
(47, 16, 'Poseable with multiple articulation points.', DATETIME('now'), 1),
(48, 16, 'Perfect for display or play.', DATETIME('now'), 1),
(49, 17, 'Educational math toy for kids.', DATETIME('now'), 1),
(50, 17, 'Encourages learning through play.', DATETIME('now'), 1),
(51, 17, 'Made from safe, durable materials.', DATETIME('now'), 1),
(52, 18, 'Classic chess board for players of all levels.', DATETIME('now'), 1),
(53, 18, 'Available in wooden and magnetic versions.', DATETIME('now'), 1),
(54, 18, 'Perfect for friendly matches and tournaments.', DATETIME('now'), 1);
