INSERT INTO product_variants_productvariant (id, title, created_at) VALUES
(1, 'iPhone 15 - 128GB', CURRENT_TIMESTAMP),
(2, 'iPhone 15 - 256GB', CURRENT_TIMESTAMP),
(3, 'MacBook Air - 13-inch', CURRENT_TIMESTAMP),
(4, 'MacBook Air - 15-inch', CURRENT_TIMESTAMP),
(5, 'Canon EOS R10 - Body Only', CURRENT_TIMESTAMP),
(6, 'Canon EOS R10 - With Lens Kit', CURRENT_TIMESTAMP),
(7, 'Mens Leather Jacket - Black', CURRENT_TIMESTAMP),
(8, 'Mens Leather Jacket - Brown', CURRENT_TIMESTAMP),
(9, 'Women''s Evening Dress - Red', CURRENT_TIMESTAMP),
(10, 'Women''s Evening Dress - Blue', CURRENT_TIMESTAMP),
(11, 'Gold Earrings - 18k', CURRENT_TIMESTAMP),
(12, 'Gold Earrings - 24k', CURRENT_TIMESTAMP),
(13, 'Modern Sofa - 3-Seater', CURRENT_TIMESTAMP),
(14, 'Modern Sofa - L-Shape', CURRENT_TIMESTAMP),
(15, 'Gardening Shovel - Small', CURRENT_TIMESTAMP),
(16, 'Gardening Shovel - Large', CURRENT_TIMESTAMP),
(17, 'Wall Painting - Abstract', CURRENT_TIMESTAMP),
(18, 'Wall Painting - Landscape', CURRENT_TIMESTAMP),
(19, 'Treadmill Pro - Standard', CURRENT_TIMESTAMP),
(20, 'Treadmill Pro - Advanced', CURRENT_TIMESTAMP),
(21, 'Camping Tent - 2 Person', CURRENT_TIMESTAMP),
(22, 'Camping Tent - 4 Person', CURRENT_TIMESTAMP),
(23, 'Football Kit - Home', CURRENT_TIMESTAMP),
(24, 'Football Kit - Away', CURRENT_TIMESTAMP),
(25, 'Moisturizing Cream - 50ml', CURRENT_TIMESTAMP),
(26, 'Moisturizing Cream - 100ml', CURRENT_TIMESTAMP),
(27, 'Lipstick Set - Matte', CURRENT_TIMESTAMP),
(28, 'Lipstick Set - Glossy', CURRENT_TIMESTAMP),
(29, 'Vitamin C Tablets - 30-pack', CURRENT_TIMESTAMP),
(30, 'Vitamin C Tablets - 60-pack', CURRENT_TIMESTAMP),
(31, 'Superhero Figure - Classic', CURRENT_TIMESTAMP),
(32, 'Superhero Figure - Limited Edition', CURRENT_TIMESTAMP),
(33, 'Math Learning Toy - Basic', CURRENT_TIMESTAMP),
(34, 'Math Learning Toy - Advanced', CURRENT_TIMESTAMP),
(35, 'Chess Board - Wooden', CURRENT_TIMESTAMP),
(36, 'Chess Board - Magnetic', CURRENT_TIMESTAMP),
(37, 'Car Phone Holder - Dashboard', CURRENT_TIMESTAMP),
(38, 'Car Phone Holder - Windshield', CURRENT_TIMESTAMP),
(39, 'Motorbike Helmet - Full Face', CURRENT_TIMESTAMP),
(40, 'Motorbike Helmet - Open Face', CURRENT_TIMESTAMP);
