# Generated by Django 4.0.2 on 2022-02-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategories', '0001_initial'),
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('max_price', models.CharField(max_length=255)),
                ('discount_price', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('long_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_stock_total', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_roles.merchant')),
                ('subcategories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategories.subcategory')),
            ],
        ),
    ]
