# Generated by Django 4.0.2 on 2022-02-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_by_merchant',
            new_name='added_by',
        ),
    ]
