# Generated by Django 5.1.2 on 2024-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_added_by_merchant_product_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
