name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_URL: emge1/allegro-clone-api
  REPO_BRANCH: main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
          ref: ${{ env.REPO_BRANCH  }}

      - name: Build Docker Image
        run: |
          docker build --build-arg REQUIREMENTS=requirements/local.txt -t ci-cd-image .

      - name: Run Tests
        run: |
          docker run --rm \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ci-cd-image \
            sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              pytest --junitxml=test-reports/results.xml
            "

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.xml

  cd:
    if: false  # temporary solution for dev
    needs: ci
    runs-on: ubuntu-latest
    steps:

      - name: Set up Terraform
        run: echo "This step is in progress"

      - name: Terraform init
        run: echo "This step is in progress"

      - name: Terraform Plan
        run: echo "This step is in progress"

      - name: Terraform Apply
        run: echo "This step is in progress"

      - name: Log in to AWS ECR
        run: echo "This step is in progress"

      - name: Build and Push Docker Image to ECR
        run: echo "This step is in progress"

      - name: Deploy to EC2
        run: echo "This step is in progress"

      - name: Verify Infrastructure State
        run: echo "This step is in progress"

      - name: Upload Deployment logs
        run: echo "This step is in progress"

      - name: Send Slack Notification
        run: echo "This step is in progress"

      - name: Failure Message
        run: echo "This step is in progress"

  postconditions:  # temporary solution
    needs: [ci, cd]
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Docker
        if: always()
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          docker network prune -f

      - name: Clean Workspace
        if: always()
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ci-cd-image \
            sh -c "rm -rf /workspace/*"

      - name: Success Message
        if: success()
        run: echo "Pipeline successfully completed"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline unsuccessful"
